bch_config:
  K: 11
  N: 15
  M: 4
  polynomial: "10011"


tbcc_config:
  K: 15
  N: 30
  V: 6
  gen_poly_1: "133"
  gen_poly_2: "171"

output_file_name: "k11n30v6_dist_spectrum.npy"

# Metadata
version: 1.0