bch_config:
  K: 51
  N: 63
  M: 12
  polynomial: "1011000111001"


tbcc_config:
  K: 63
  N: 126
  V: 8
  gen_poly_1: "561"
  gen_poly_2: "753"

output_file_name: "k51n126v8_dist_spectrum.npy"

# Metadata
version: 1.0